### ISSUE TITLE
Can't get datum from Ogmios Query

### ISSUE THREAD

**Issue by vvtran** [Plutonomicon/cardano-browser-tx#257] opened 2022-03-31 17:59 UTC
Running `npm run dev` on `viet/seabug-deployment-test-datum-hash`. The lookups logic appears to struggle with `mustSpendScriptOutput` as a result of not being able to successfully query datum from the datumHash via `getDatumByHash :: DatumHash -> QueryM (Maybe PlutusData)`, it's unclear to why it's not working but the following is logged:
```
sending:  {"type":"jsonwsp/request","version":"1.0","servicename":"ogmios","methodname":"GetDatumByHash","args":{"hash":"961d7ebd383bef116ef9bcb527f1bc1a4587f819d4ec0e723fef5ab228ad1d8f"}}

message:  {"methodname":"GetDatumByHash","result":{"DatumNotFound":null},"servicename":"ogmios-datum-cache","version":"1.0","type":"jsonwsp/response"}
```
See the `MustSpendScriptOutput` case of `Types.ScriptLookups.processConstraint`, a call to `getDatumByHash` is where it seems to crash. You can test this by logging before and after.

**Comment by ngua** [comment] 2022-04-01 04:59
I'm going to close this for now since I've confirmed that ogmios-datum-cache works as expected after syncing using curl commands. If there is another bug with our WS interface to ogmios-datum-cache (e.g. deserialization failure), please re-open this with the specific error

**Closed by ngua** 2022-04-01 04:59 UTC
